[package]
name = "comp"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = "0.20"

[dependencies]
clap = { version = "4.4", features = ["derive", "env"] }
lalrpop-util = { version = "0.20", features = ["lexer"] }
